/**
 * The type contract for the entire OS.
 *
 * Every surface — rail, tabs, command palette, terminal filesystem, routes,
 * and OG images — is derived from objects shaped by these interfaces. Adding
 * a project means adding one `Project`; it then appears everywhere at once.
 */

export type ModuleId = "readme" | "projects" | "stack" | "timeline" | "contact" | "now";

export interface OSModule {
  id: ModuleId;
  /** Two-letter code shown in the collapsed rail. */
  code: string;
  /** Lowercase label used in the rail and palette. */
  label: string;
  /** Filename shown in the tab strip — this is the "document" metaphor. */
  file: string;
  route: string;
  /** One-line description used in the palette and page metadata. */
  description: string;
  /** Extra terms the palette should match on. */
  keywords: string[];
}

export type ProjectStatus = "live" | "archived" | "wip" | "internal";

/** Coarse tags used by the projects index filter bar. A repo can carry more
 *  than one — inferred from language + README content, never hand-curated. */
export type ProjectCategory = "web" | "mobile" | "ai" | "open-source" | "experiment";

/** One real commit, trimmed to what's worth showing — the git-activity
 *  section reads these directly instead of synthesizing a fake log. */
export interface GitHubCommit {
  sha: string;
  message: string;
  date: string;
  url: string;
}

/**
 * The evidence GitHub actually provides, kept separate from the hand-authored
 * narrative fields above it in `Project` — this block is never edited by
 * hand, only regenerated by `scripts/sync-github.ts`. Absent entirely for a
 * `Project` that isn't backed by a real repository.
 */
export interface GitHubMeta {
  stars: number;
  forks: number;
  watchers: number;
  openIssues: number;
  createdAt: string;
  updatedAt: string;
  topics: string[];
  license?: string;
  defaultBranch: string;
  isFork: boolean;
  isArchived: boolean;
  languages: string[];
  categories: ProjectCategory[];
  commits: GitHubCommit[];
}

/**
 * Deliberately shaped to be printed almost verbatim as the file's own source
 * — the project *is* this object; the UI never invents content the object
 * doesn't have. Chrome-only facts (slug, year, status, featured) live outside
 * it because a real config object wouldn't describe its own filename or the
 * curation logic that lists it.
 */
export interface Project {
  slug: string;
  year: string;
  status: ProjectStatus;
  /** Featured projects surface in the README's "selected work". Keep to 3. */
  featured: boolean;

  name: string;
  /** One or two sentences. Doubles as the list-row blurb and OG description. */
  description: string;
  problem: string;
  /** Ordered steps — how the problem was actually approached. */
  solution: string[];
  role: string;
  technologies: string[];
  /** What the thing does, from a user's seat — not how it was built. */
  features: string[];
  /** How it was actually built — the decisions, not a component diagram. */
  architecture: string[];
  /** Concrete technical obstacles, not generic "it was hard." */
  challenges: string[];
  /** Outcomes with numbers where there are real numbers to give. */
  results: string[];
  /** What carries forward to the next project — distinct from `challenges`:
   *  those are what went wrong, these are what was learned from it. */
  lessons: string[];
  /** Image paths. Empty is fine and renders an honest placeholder — never faked. */
  screenshots: string[];
  links: {
    live?: string;
    github?: string;
  };
  /** Optional honesty note — what you'd do differently. Recruiters notice. */
  retro?: string;
  /** Present only for repos synced from GitHub. Real stars, real commits —
   *  the evidence. Everything above it in this object is still the story. */
  github?: GitHubMeta;
}

/**
 * The GitHub profile block shown on the README. GitHub's own fields (`bio`,
 * `location`) are trusted only when they're not empty and not the literal
 * placeholder text GitHub ships new accounts with — otherwise the existing
 * hand-authored `Profile` fields win. Never two sources disagreeing on screen.
 */
export interface GitHubProfile {
  login: string;
  name: string | null;
  avatarUrl: string;
  bio: string | null;
  location: string | null;
  blog: string | null;
  htmlUrl: string;
  followers: number;
  following: number;
  publicRepos: number;
}

/**
 * A yearly reinterpretation of the contribution graph, not a copy of it —
 * see `Now.tsx`. Only ever produced when `GITHUB_TOKEN` is set and the
 * GraphQL call succeeds; absent (not zeroed) otherwise so the UI can hide
 * the section instead of showing confident-looking zeros.
 */
/**
 * The hand-authored half of a GitHub-sourced project — everything a repo's
 * metadata and README can't tell you. Every field optional: an unstarted
 * story just means the project page shows GitHub's evidence on its own and
 * an honest "not written yet" where the narrative would go, rather than a
 * fabricated one. See `content/project-stories.ts`.
 */
export interface ProjectStory {
  role?: string;
  /** Overrides the README-derived description when set. */
  description?: string;
  problem?: string;
  solution?: string[];
  architecture?: string[];
  challenges?: string[];
  results?: string[];
  lessons?: string[];
  retro?: string;
  /** Overrides the auto-derived status (e.g. call a `wip` repo `live` once
   *  it's actually usable, or vice versa). */
  status?: ProjectStatus;
  /** A demo URL when the repo doesn't set GitHub's own `homepage` field. */
  live?: string;
}

export interface ActivityStats {
  year: number;
  totalCommits: number;
  totalPRs: number;
  totalIssues: number;
  totalReviews: number;
  reposActive: number;
}

/** One row of the `/dev/now` status table — `label` is the fixed left-hand
 *  word ("Building", "Learning", …), `value` is the only part that changes. */
export interface NowFocusItem {
  label: string;
  value: string;
}

/** A name plus the one line that explains it — used for both `favoriteTech`
 *  (taste, not proficiency — see `stack.ts` for the honest ratings) and
 *  `experiments` (small, finished-or-not side projects). */
export interface NowLink {
  name: string;
  note: string;
  href?: string;
}

export interface Now {
  /** Hand-set, not computed — the point is that a stale date is visible. */
  updated: string;
  focus: NowFocusItem[];
  favoriteTech: NowLink[];
  preferences: string[];
  principles: string[];
  experiments: NowLink[];
  /** One human paragraph. Signed, not corporate. */
  note: string;
}

export interface StackItem {
  name: string;
  /** 1–5, rendered as five blocks. Be honest; 5 means you'd teach it. */
  level: 1 | 2 | 3 | 4 | 5;
  years: string;
  note: string;
}

export interface StackGroup {
  id: string;
  label: string;
  blurb: string;
  items: StackItem[];
}

export type TimelineKind = "work" | "education" | "project" | "milestone";

export interface TimelineEntry {
  id: string;
  from: string;
  /** "present" renders as a live marker. */
  to: string;
  org: string;
  role: string;
  kind: TimelineKind;
  location?: string;
  bullets: string[];
  stack?: string[];
}

export interface Social {
  label: string;
  handle: string;
  href: string;
}

export interface Profile {
  /** Short username, kept for reference — the terminal prompt itself reads
   *  `visitor@{host}`, since it's a guest shell on this machine, not mine. */
  handle: string;
  /** Hostname — the OS wordmark. */
  host: string;
  version: string;
  name: string;
  role: string;
  /** The single sentence that positions you. Make it specific. */
  positioning: string;
  bio: string[];
  location: string;
  /** IANA zone — drives the live clock and the availability indicator. */
  timezone: string;
  timezoneLabel: string;
  experience: string;
  availability: {
    state: "open" | "selective" | "closed";
    label: string;
    detail: string;
    responseTime: string;
  };
  email: string;
  resume: string;
  socials: Social[];
  currently: string[];
}

/* ── Virtual filesystem, derived from the content above ─────────────── */

export type VFileKind =
  | "readme"
  | "project"
  | "stack"
  | "timeline"
  | "contact"
  | "resume"
  | "now";

export interface VFile {
  type: "file";
  name: string;
  kind: VFileKind;
  /** Slug for `kind: "project"`; unused otherwise. */
  ref?: string;
  /** Bytes — fabricated but stable, so `ls -l` looks right. */
  size: number;
  route?: string;
}

export interface VDir {
  type: "dir";
  name: string;
  children: VNode[];
}

export type VNode = VFile | VDir;

/* ── Search / palette index ─────────────────────────────────────────── */

export interface IndexEntry {
  id: string;
  type: "module" | "project";
  title: string;
  subtitle: string;
  route: string;
  keywords: string[];
}
